const notebook=document.querySelector('#notebook'),output=document.querySelector('#output'),status=document.querySelector('#status'),documents=document.querySelector('#documents'),saveState=document.querySelector('#save-state');let sourceText='',currentPath='',saveTimer;
const escape=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});return r.json()}
function prose(text){return text.split('\n').map(line=>{if(!line)return '';if(line.startsWith('# '))return `<h1>${escape(line.slice(2))}</h1>`;if(line.startsWith('## '))return `<h2>${escape(line.slice(3))}</h2>`;return `<p>${escape(line).replace(/`([^`]+)`/g,'<code>$1</code>')}</p>`}).join('')}
function renderNotebook(){let pieces=[],cursor=0,re=/```([\w+-]+)\s*(\{[^}]*#([\w-]+)[^}]*\})\n([\s\S]*?)```/g,m;while((m=re.exec(sourceText))){if(m.index>cursor)pieces.push(`<article class="narrative" contenteditable="true" data-narrative>${prose(sourceText.slice(cursor,m.index).replace(/^---[\s\S]*?---\n?/,''))}</article>`);pieces.push(`<article class="notebook-cell"><header><span>${escape(m[1])}</span><span>cell · ${escape(m[3])}</span><button data-run-cell="${escape(m[3])}">Run cell</button></header><textarea data-cell="${escape(m[3])}" spellcheck="false">${escape(m[4])}</textarea></article>`);cursor=re.lastIndex}if(cursor<sourceText.length)pieces.push(`<article class="narrative" contenteditable="true" data-narrative>${prose(sourceText.slice(cursor))}</article>`);notebook.innerHTML=pieces.join('')}
function narrativeSource(block){return [...block.children].map(node=>node.tagName==='H1'?`# ${node.innerText}`:node.tagName==='H2'?`## ${node.innerText}`:node.innerText).join('\n\n')+'\n\n'}
function currentSource(){const front=(sourceText.match(/^---[\s\S]*?---\n?/)||[''])[0],narratives=[...document.querySelectorAll('[data-narrative]')],cells=[...document.querySelectorAll('[data-cell]')];let result=front;for(let i=0;i<cells.length;i++){result+=narrativeSource(narratives[i]||document.createElement('div'));const cell=cells[i],match=sourceText.match(new RegExp('```([\\w+-]+)\\s*(\\{[^}]*#'+cell.dataset.cell+'[^}]*\\})'));if(match)result+=`\`\`\`${match[1]} ${match[2]}\n${cell.value}\`\`\`\n\n`}return result+narrativeSource(narratives[cells.length]||document.createElement('div'))}
function dirty(){saveState.textContent='UNSAVED';clearTimeout(saveTimer);saveTimer=setTimeout(save,900)}
async function save(){if(!currentPath)return;saveState.textContent='SAVING';const result=await api('/api/save',{path:currentPath,source:currentSource()});saveState.textContent=result.ok?'SAVED':'SAVE FAILED';if(result.ok)sourceText=currentSource()}
async function load(path){const data=await api('/api/document?path='+encodeURIComponent(path));currentPath=data.path;sourceText=data.source;renderNotebook();saveState.textContent='SAVED'}
async function initialize(){const data=await api('/api/files');documents.innerHTML=data.files.map(path=>`<option value="${escape(path)}">${escape(path)}</option>`).join('');documents.onchange=()=>load(documents.value);await load(data.files[0]||'example.pmd')}
function rich(item){if(['png','jpg','jpeg','svg'].includes(item.kind))return `<div class="rich"><img alt="${item.name}" src="data:image/${item.kind==='svg'?'svg+xml':item.kind};base64,${item.data}"></div>`;if(item.kind==='md')return `<div class="rich">${prose(item.data)}</div>`;return `<div class="rich"><pre>${escape(item.data||('Attachment: '+item.name))}</pre></div>`}
function cellResult(c){return `<article class="cell"><div class="cell-title"><b>${c.id}</b><span class="${c.status}">${c.status.toUpperCase()}</span></div>${c.stdout?`<pre class="stream">${escape(c.stdout)}</pre>`:''}${c.stderr?`<pre class="stream stderr">${escape(c.stderr)}</pre>`:''}${(c.outputs||[]).map(rich).join('')}</article>`}
function clearInlineResults(){document.querySelectorAll('[data-inline-result]').forEach(node=>node.remove())}
async function call(path,body){status.textContent='RUNNING';output.className='empty';output.textContent='Executing isolated processes...';if(!path.includes('check'))clearInlineResults();const d=await api(path,body);status.textContent=d.ok?'COMPLETE':'ATTENTION';if(path.includes('check')){output.innerHTML=d.ok?'<div class="empty">Valid PMD document. Graph and engine checks passed.</div>':`<pre class="stream stderr">${escape(d.errors.join('\n'))}</pre>`;return}if(d.errors?.length){output.innerHTML=`<pre class="stream stderr">${escape(d.errors.join('\n'))}</pre>`;return}for(const c of d.cells){const host=document.querySelector(`[data-cell="${CSS.escape(c.id)}"]`)?.closest('.notebook-cell');if(host)host.insertAdjacentHTML('afterend',`<div data-inline-result>${cellResult(c)}</div>`)}output.innerHTML='<div class="empty">Results are shown directly beneath their cells.</div>'}
notebook.addEventListener('input',dirty);notebook.addEventListener('click',e=>{if(e.target.dataset.runCell)call('/api/run',{source:currentSource(),cell:e.target.dataset.runCell})});document.querySelector('#save').onclick=save;document.querySelector('#run').onclick=()=>call('/api/run',{source:currentSource()});document.querySelector('#test').onclick=()=>call('/api/run',{source:currentSource(),tests:true});document.querySelector('#check').onclick=()=>call('/api/check',{source:currentSource()});initialize();
