const notebook=document.querySelector('#notebook'),output=document.querySelector('#output'),status=document.querySelector('#status'),documents=document.querySelector('#documents'),saveState=document.querySelector('#save-state');let sourceText='',currentPath='',saveTimer;
const escape=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});return r.json()}
function prose(text){return text.split('\n').map(line=>{if(!line)return '';if(line.startsWith('# '))return `<h1>${escape(line.slice(2))}</h1>`;if(line.startsWith('## '))return `<h2>${escape(line.slice(3))}</h2>`;return `<p>${escape(line).replace(/`([^`]+)`/g,'<code>$1</code>')}</p>`}).join('')}
function actions(){return '<span class="cell-actions"><button data-move-block="up" title="Move block up">Up</button><button data-move-block="down" title="Move block down">Down</button><button data-add-text title="Add Markdown block below">Add text</button><button data-add-code title="Add code cell below">Add code</button><button data-delete-block title="Delete this block">Delete</button></span>'}
function attributeValue(attrs,name){const match=new RegExp('(?:^|\\s)'+name+'=([^\\s}]+)').exec(attrs);return match?match[1]:''}
function attrsFromFence(attrs,id){return {id,language:'',depends:attributeValue(attrs,'depends-on'),uses:attributeValue(attrs,'uses'),role:attributeValue(attrs,'role')||'code',testOf:attributeValue(attrs,'test-of'),tags:attributeValue(attrs,'tags'),independent:/(?:^|\s)independent=true(?:\s|$)/.test(attrs)}}
function selected(value,option){return value===option?' selected':''}
function metadata(attrs,id,language){const data=attrsFromFence(attrs,id);data.language=language;return `<details class="cell-settings"><summary>Cell settings</summary><div class="settings-grid"><label>Language<input data-meta="language" value="${escape(data.language)}"></label><label>Cell ID<input data-meta="id" value="${escape(data.id)}"></label><label>Depends on<input data-meta="depends" placeholder="fetch,prepare" value="${escape(data.depends)}"></label><label>Uses libraries<input data-meta="uses" placeholder="helpers" value="${escape(data.uses)}"></label><label>Role<select data-meta="role"><option${selected(data.role,'code')}>code</option><option${selected(data.role,'setup')}>setup</option><option${selected(data.role,'test')}>test</option><option${selected(data.role,'scratch')}>scratch</option><option${selected(data.role,'lib')}>lib</option></select></label><label>Test of<input data-meta="test-of" placeholder="compute" value="${escape(data.testOf)}"></label><label>Tags<input data-meta="tags" placeholder="daily,slow" value="${escape(data.tags)}"></label><label class="check"><input data-meta="independent" type="checkbox"${data.independent?' checked':''}> Independent root</label></div></details>`}
function markdownCell(source){return `<article class="markdown-cell"><header><span>Markdown</span>${actions()}</header><textarea data-narrative spellcheck="true">${escape(source)}</textarea><div class="markdown-preview">${prose(source)}</div></article>`}
function codeCell(language,attrs,id,source){const data=attrsFromFence(attrs,id),runLabel=data.role==='test'?'Run test':'Run cell';return `<article class="notebook-cell"><header><span class="cell-language">${escape(language)}</span><span class="cell-id">${escape(id)}</span>${actions()}<button data-run-cell="${escape(id)}">${runLabel}</button></header>${metadata(attrs,id,language)}<div class="code-editor" data-language="${escape(language)}"><pre class="highlight" aria-hidden="true"></pre><textarea data-cell="${escape(id)}" spellcheck="false">${escape(source)}</textarea></div></article>`}
async function highlightCell(cell){const layer=cell.previousElementSibling;if(!layer)return;layer.textContent=cell.value;const request=cell.dataset.highlightRequest=(cell.dataset.highlightRequest||0)+1;const result=await api('/api/highlight',{language:cell.closest('.code-editor').dataset.language,source:cell.value});if(result.ok&&cell.dataset.highlightRequest==request)layer.innerHTML=result.html}
function renderNotebook(){let pieces=[],cursor=0,re=/```([\w+-]+)\s*(\{[^}]*#([\w-]+)[^}]*\})\n([\s\S]*?)```/g,m;while((m=re.exec(sourceText))){if(m.index>cursor)pieces.push(markdownCell(sourceText.slice(cursor,m.index).replace(/^---[\s\S]*?---\n?/,'')));pieces.push(codeCell(m[1],m[2],m[3],m[4]));cursor=re.lastIndex}if(cursor<sourceText.length)pieces.push(markdownCell(sourceText.slice(cursor)));notebook.innerHTML=pieces.join('');document.querySelectorAll('[data-cell]').forEach(highlightCell)}
function cellAttributes(block){const value=name=>block.querySelector(`[data-meta="${name}"]`)?.value.trim()||'',parts=[`#${value('id')}`];for(const [name,key] of [['depends-on','depends'],['uses','uses'],['role','role'],['test-of','test-of'],['tags','tags']]){const item=value(key);if(item&&(name!=='role'||item!=='code'))parts.push(`${name}=${item}`)}if(block.querySelector('[data-meta="independent"]')?.checked)parts.push('independent=true');return `{${parts.join(' ')}}`}
function currentSource(){const front=(sourceText.match(/^---[\s\S]*?---\n?/)||[''])[0];let result=front;for(const block of notebook.children){const narrative=block.querySelector('[data-narrative]');if(narrative){result+=narrative.value.replace(/\s+$/,'')+'\n\n';continue}const cell=block.querySelector('[data-cell]'),language=block.querySelector('[data-meta="language"]').value.trim()||'python';result+=`\`\`\`${language} ${cellAttributes(block)}\n${cell.value}\`\`\`\n\n`}return result}
function dirty(){saveState.textContent='UNSAVED';clearTimeout(saveTimer);saveTimer=setTimeout(save,900)}
async function save(){if(!currentPath)return;saveState.textContent='SAVING';const result=await api('/api/save',{path:currentPath,source:currentSource()});saveState.textContent=result.ok?'SAVED':'SAVE FAILED';if(result.ok)sourceText=currentSource()}
async function load(path){const data=await api('/api/document?path='+encodeURIComponent(path));currentPath=data.path;sourceText=data.source;renderNotebook();saveState.textContent='SAVED'}
async function initialize(){const data=await api('/api/files');documents.innerHTML=data.files.map(path=>`<option value="${escape(path)}">${escape(path)}</option>`).join('');documents.onchange=()=>load(documents.value);if(data.files[0])await load(data.files[0])}
function rich(item){if(['png','jpg','jpeg','svg'].includes(item.kind))return `<div class="rich"><img alt="${item.name}" src="data:image/${item.kind==='svg'?'svg+xml':item.kind};base64,${item.data}"></div>`;if(item.kind==='md')return `<div class="rich">${prose(item.data)}</div>`;return `<div class="rich"><pre>${escape(item.data||('Attachment: '+item.name))}</pre></div>`}
function cellResult(c){return `<article class="cell"><div class="cell-title"><b>${c.id}</b><span class="${c.status}">${c.status.toUpperCase()}</span></div>${c.stdout?`<pre class="stream">${escape(c.stdout)}</pre>`:''}${c.stderr?`<pre class="stream stderr">${escape(c.stderr)}</pre>`:''}${(c.outputs||[]).map(rich).join('')}</article>`}
function clearInlineResults(){document.querySelectorAll('[data-inline-result]').forEach(node=>node.remove())}
function nextCellId(){let index=1,ids=[...document.querySelectorAll('[data-meta="id"]')].map(input=>input.value);while(ids.includes(`cell-${index}`))index++;return `cell-${index}`}
function refreshAfterStructureChange(){clearInlineResults();sourceText=currentSource();renderNotebook();dirty()}
function addCodeAfter(block){const id=nextCellId();block.insertAdjacentHTML('afterend',codeCell('python',`{#${id}}`,id,'# New cell'));refreshAfterStructureChange();document.querySelector(`[data-cell="${CSS.escape(id)}"]`)?.focus()}
function addTextAfter(block){block.insertAdjacentHTML('afterend',markdownCell('# New markdown cell'));refreshAfterStructureChange();block.nextElementSibling?.querySelector('[data-narrative]')?.focus()}
function moveBlock(block,direction){const blocks=[...notebook.querySelectorAll(':scope > .notebook-cell,:scope > .markdown-cell')],index=blocks.indexOf(block),target=blocks[index+(direction==='up'?-1:1)];if(!target)return;if(direction==='up')notebook.insertBefore(block,target);else notebook.insertBefore(target,block);refreshAfterStructureChange()}
function deleteBlock(block){block.remove();refreshAfterStructureChange()}
function renameCell(input){const block=input.closest('.notebook-cell'),old=block.querySelector('[data-cell]').dataset.cell,next=input.value.trim();if(!next||old===next)return;for(const dependent of document.querySelectorAll('[data-meta="depends"]'))dependent.value=dependent.value.split(',').map(id=>id.trim()===old?next:id.trim()).filter(Boolean).join(',');for(const test of document.querySelectorAll('[data-meta="test-of"]'))if(test.value.trim()===old)test.value=next;block.querySelector('[data-cell]').dataset.cell=next;block.querySelector('.cell-id').textContent=next;block.querySelector('[data-run-cell]').dataset.runCell=next}
function showDiagnostics(errors){const remaining=[];for(const message of errors){const match=/^([^:]+):\s/.exec(message),host=match&&document.querySelector(`[data-cell="${CSS.escape(match[1])}"]`)?.closest('.notebook-cell');if(host)host.insertAdjacentHTML('afterend',`<div data-inline-result><pre class="stream stderr">${escape(message)}</pre></div>`);else remaining.push(message)}return remaining}
async function call(path,body){status.textContent='RUNNING';output.className='empty';output.textContent='Executing isolated processes...';clearInlineResults();const d=await api(path,body);status.textContent=d.ok?'COMPLETE':'ATTENTION';const remaining=showDiagnostics(d.errors||[]);if(path.includes('check')){output.innerHTML=d.ok?'<div class="empty">Valid PMD document. Graph and engine checks passed.</div>':remaining.length?`<pre class="stream stderr">${escape(remaining.join('\n'))}</pre>`:'<div class="empty">Diagnostics are shown beneath the affected cells.</div>';return}for(const c of d.cells||[]){const host=document.querySelector(`[data-cell="${CSS.escape(c.id)}"]`)?.closest('.notebook-cell');if(host)host.insertAdjacentHTML('afterend',`<div data-inline-result>${cellResult(c)}</div>`)}output.innerHTML=remaining.length?`<pre class="stream stderr">${escape(remaining.join('\n'))}</pre>`:'<div class="empty">Results and diagnostics are shown directly beneath their cells.</div>'}
function runCell(id){const block=document.querySelector(`[data-cell="${CSS.escape(id)}"]`)?.closest('.notebook-cell'),tests=block?.querySelector('[data-meta="role"]')?.value==='test';call('/api/run',{source:currentSource(),cell:id,tests})}
notebook.addEventListener('input',e=>{dirty();if(e.target.matches('[data-cell]'))highlightCell(e.target);if(e.target.matches('[data-narrative]'))e.target.nextElementSibling.innerHTML=prose(e.target.value);if(e.target.matches('[data-meta="id"]'))renameCell(e.target);if(e.target.matches('[data-meta="language"]')){const block=e.target.closest('.notebook-cell');block.querySelector('.cell-language').textContent=e.target.value;block.querySelector('.code-editor').dataset.language=e.target.value;highlightCell(block.querySelector('[data-cell]'))}});notebook.addEventListener('change',e=>{if(e.target.matches('[data-meta="role"]')){const block=e.target.closest('.notebook-cell');block.querySelector('[data-run-cell]').textContent=e.target.value==='test'?'Run test':'Run cell';dirty()}});notebook.addEventListener('scroll',e=>{if(e.target.matches('[data-cell]')){const layer=e.target.previousElementSibling;layer.scrollTop=e.target.scrollTop;layer.scrollLeft=e.target.scrollLeft}},true);notebook.addEventListener('click',e=>{const block=e.target.closest('.notebook-cell,.markdown-cell');if(e.target.dataset.runCell)runCell(e.target.dataset.runCell);else if(e.target.dataset.addCode)addCodeAfter(block);else if(e.target.dataset.addText)addTextAfter(block);else if(e.target.dataset.deleteBlock)deleteBlock(block);else if(e.target.dataset.moveBlock)moveBlock(block,e.target.dataset.moveBlock)});document.addEventListener('keydown',e=>{const cell=e.target.closest?.('[data-cell]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if(cell&&(e.ctrlKey||e.metaKey||e.shiftKey)&&e.key==='Enter'){e.preventDefault();runCell(cell.dataset.cell);if(e.shiftKey){const cells=[...document.querySelectorAll('[data-cell]')],next=cells[cells.indexOf(cell)+1];next?.focus()}}});document.querySelector('#save').onclick=save;document.querySelector('#run').onclick=()=>call('/api/run',{source:currentSource()});document.querySelector('#test').onclick=()=>call('/api/run',{source:currentSource(),tests:true});document.querySelector('#check').onclick=()=>call('/api/check',{source:currentSource()});initialize();
